name: Node.js Package

on: 
  push:
    branches: [main]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:

  buildClient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --force
        working-directory: ClientApp
      - run: npm audit fix --force
        working-directory: ClientApp
      - run: npm test
        working-directory: ClientApp
      - run: npm run build
        working-directory: ClientApp
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: Artifact_ClientApp
          path: ClientApp/build
        
  buildServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
        working-directory: Server
      - run: npm run build
        working-directory: Server
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: Artifact_Server
          path: Server/build
        
        
        
        
        
        
